"""email_verificado

Revision ID: b63d0a399c7e
Revises: 7c3e9a2d4f10
Create Date: 2026-09-23 12:12:26.522493

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b63d0a399c7e'
down_revision: Union[str, None] = '7c3e9a2d4f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Las filas ya existentes no pueden quedar en NULL: se marcan como no
    # verificadas para evitar romper cuentas activas antiguas.
    op.add_column(
        'usuarios',
        sa.Column('email_verificado', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('usuarios', sa.Column('codigo_verificacion', sa.String(length=20), nullable=True))
    op.execute("UPDATE usuarios SET email_verificado = FALSE WHERE email_verificado IS NULL")
    op.alter_column('usuarios', 'email_verificado', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'codigo_verificacion')
    op.drop_column('usuarios', 'email_verificado')
    # ### end Alembic commands ###
