"""crear tablas iniciales

Revision ID: ef6f00ca0b57
Revises: 
Create Date: 2026-07-08 03:31:05.344860

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ef6f00ca0b57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sesiones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('netlist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('instrucciones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('historial_chat', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('modo_detectado', sa.String(length=20), nullable=True),
    sa.Column('metricas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_mensajes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sesion_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('modo_detectado', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_mensajes')
    op.drop_table('sesiones')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
